[account]
host = "192.168.2.125"
port = 27017
db = "QAREALTIME"

[hisdata]
host = "192.168.2.118"
port = 27017
db = "quantaxis"

[mq]
host = "192.168.2.125"
port = 5672
user = "admin"
password = "admin"

[redis]
host = "192.168.2.125"
port = 6379

[cli]
name = ["t01"]
codes = ["i2009"]
freqs = ['1min','5min']
params = 'default'